version: "3.8"



services:
  mongo:
    image: mongo:latest
    container_name: yolo-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-net

  backend:
    image: glen510/yolo-backend:v1.0.0
    container_name: yolo-backend
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/yolo_db
    networks:
      - app-net

  client:
    image: glen510/yolo-client:v1.0.0
    container_name: yolo-client
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-net

volumes:
  mongo-data:

networks:
  app-net:
    driver: bridge
