---
- name: Clone frontend code from GitHub
  git:
    repo: https://github.com/G-OMONDI/yolo.git
    dest: "{{ app_directory }}"
    version: main

- name: Pull frontend Docker image
  docker_image:
    name: "{{ frontend_image }}"
    source: pull

- name: Run frontend container
  docker_container:
    name: frontend
    image: "{{ frontend_image }}"
    state: started
    restart_policy: always
    ports:
      - "3000:3000"
    volumes:
      - "{{ app_directory }}/frontend:/usr/src/app"
- name: Ensure frontend app directory exists
  file: 