---
- name: Clone frontend code from GitHub
  git:
    repo: https://github.com/G-OMONDI/yolo.git
    dest: "{{ app_directory }}"
    version: main

- name: Pull frontend Docker image
  docker_image:
    name: "glen510/yolo-client:v1.0.0"
    source: pull

- name: Run frontend container
  docker_container:
    name: frontend
    image: "glen510/yolo-client:v1.0.0"
    state: started
    restart_policy: always
    ports:
      - "3000:3000"
    volumes:
      - "{{ app_directory }}/frontend:/usr/src/app"
- name: Ensure frontend app directory exists
  file: 