
- name: Pull MongoDB image
  community.docker.docker_image:
    name: mongo:latest
    source: pull

- name: Run MongoDB container
  community.docker.docker_container:
    name: mongo
    image: mongo:latest
    state: started
    restart_policy: always
    published_ports:
      - "27017:27017"
    volumes:
      - "{{ mongo_data_dir | default('/home/glen/development/code/dev10/yolo/data/db') }}:/data/db"
    env:
      MONGO_INITDB_ROOT_USERNAME: "{{ mongo_root_username | default('root') }}"
      MONGO_INITDB_ROOT_PASSWORD: "{{ mongo_root_password | default('example') }}"
  tags: mongo
