apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  labels:
    app: myapp
data:
  APP_NAME: "E-Commerce Dashboard"
  APP_ENV: "production"
  API_URL: "http://backend-service:5000"
  FRONTEND_PORT: "3000"
  DATABASE_URL: "mongodb://mongo-data:27017/mydatabase"
  LOG_LEVEL: "info"
  FEATURE_FLAG: "true"
  MAINTENANCE_MODE: "false"
  