apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: app-namespace
spec:
  clusterIP: None   # Headless service (no single ClusterIP)
  selector:
    app: mongo
  ports:
    - name: mongo
      port: 27017
      targetPort: 27017
