apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  labels:
    app: myapp
type: Opaque
data:
  MONGO_USER: bW9uZ291c2Vy       # base64 for 'mongouser'
  MONGO_PASSWORD: c2VjdXJlcGFzcw== # base64 for 'securepass'
  JWT_SECRET: c3VwZXJzZWNyZXRrZXk= # base64 for 'supersecretkey'
